import type { GameCardItem } from "./game-card-item";

/** Danh sách game slot — `image` / `logo` trỏ vào `public/images/slot/`. */
export const SLOT_GAMES: GameCardItem[] = [
  {
    id: "slot-01",
    image: "/images/slot/PragmaticPlay.webp",
    title: "프라그마틱",
    logo: "/images/slot/logo/pragmatic_slot.webp",
    vendorId: "PragmaticPlay",
  },
  {
    id: "slot-02",
    image: "/images/slot/BigTimeGaming.webp",
    title: "빅타임게이밍",
    logo: "/images/slot/logo/habanero_slot.webp",
    vendorId: "BigTimeGaming",
  },
  {
    id: "slot-03",
    image: "/images/slot/Booongo.webp",
    title: "부운고",
    logo: "/images/slot/logo/btg_slot.webp",
    vendorId: "Booongo",
  },
  {
    id: "slot-04",
    image: "/images/slot/Evoplay.webp",
    title: "에보플레이",
    logo: "/images/slot/logo/relax_slot.webp",
    vendorId: "Evoplay",
  },
  {
    id: "slot-05",
    image: "/images/slot/YGGDrasil.webp",
    title: "이그드라실",
    logo: "/images/slot/logo/nextspin_slot.webp",
    vendorId: "YGGDrasil",
  },
  {
    id: "slot-06",
    image: "/images/slot/리얼타임 게이밍.webp",
    title: "리얼타임 게이밍",
    logo: "/images/slot/logo/리얼타임 게이밍.webp",
    vendorId: "playngovx",
  },
  {
    id: "slot-07",
    image: "/images/slot/QuickSpin.webp",
    title: "퀵스핀",
    logo: "/images/slot/logo/hacksaw_slot.webp",
    vendorId: "QuickSpin",
  },
  {
    id: "slot-08",
    image: "/images/slot/NetEnt.webp",
    title: "넷엔트",
    logo: "/images/slot/logo/avatarux_slot.webp",
    vendorId: "NetEnt",
  },
  {
    id: "slot-09",
    image: "/images/slot/RedTiger.webp",
    title: "레드타이거",
    logo: "/images/slot/logo/bng_slot.webp",
    vendorId: "RedTiger",
  },
  {
    id: "slot-10",
    image: "/images/slot/Habanero.webp",
    title: "하바네로",
    logo: "/images/slot/logo/cq9_slot.webp",
    vendorId: "Habanero",
  },
  {
    id: "slot-11",
    image: "/images/slot/PlaynGo.webp",
    title: "플레이앤고",
    logo: "/images/slot/logo/pgsoft_slot.webp",
    vendorId: "PlaynGo",
  },
  {
    id: "slot-12",
    image: "/images/slot/RelaxGaming.webp",
    title: "릴렉스 게이밍",
    logo: "/images/slot/logo/ag_slot.webp",
    vendorId: "RelaxGaming",
  },
  {
    id: "slot-13",
    image: "/images/slot/GameArt.webp",
    title: "게임아트",
    logo: "/images/slot/logo/skywind_slot.webp",
    vendorId: "GameArt",
  },
  {
    id: "slot-14",
    image: "/images/slot/CQ9.webp",
    title: "CQ9",
    logo: "/images/slot/logo/reelplay_slot.webp",
    vendorId: "CQ9",
  },
  {
    id: "slot-15",
    image: "/images/slot/PlayStar.webp",
    title: "플레이스타",
    logo: "/images/slot/logo/gpi_slot.webp",
    vendorId: "PlayStar",
  },
  {
    id: "slot-16",
    image: "/images/slot/PGSoft.webp",
    title: "PG소프트",
    logo: "/images/slot/logo/dragoonsoft_slot.webp",
    vendorId: "PGSoft",
  },
  {
    id: "slot-17",
    image: "/images/slot/Genesis.webp",
    title: "제네시스",
    logo: "/images/slot/logo/simpleplay_slot.webp",
    vendorId: "Genesis",
  },
  {
    id: "slot-18",
    image: "/images/slot/MicrogamingSlot.webp",
    title: "마이크로게이밍",
    logo: "/images/slot/logo/slotmill_slot.webp",
    vendorId: "MicrogamingSlot",
  },
  {
    id: "slot-19",
    image: "/images/slot/BlueprintGaming.webp",
    title: "블루프린트",
    logo: "/images/slot/logo/1x2_slot.webp",
    vendorId: "BlueprintGaming",
  },
  {
    id: "slot-20",
    image: "/images/slot/ElkStudios.webp",
    title: "ELK 스튜디오",
    logo: "/images/slot/logo/office_slot.webp",
    vendorId: "ElkStudios",
  },
  {
    id: "slot-21",
    image: "/images/slot/NoLimitCity.webp",
    title: "노리밋시티",
    logo: "/images/slot/logo/playngo_slot.webp",
    vendorId: "NoLimitCity",
  },
  {
    id: "slot-22",
    image: "/images/slot/Revolver.webp",
    title: "리볼버 게이밍",
    logo: "/images/slot/logo/office_slot.webp",
    vendorId: "revolver",
  },
  {
    id: "slot-23",
    image: "/images/slot/1x2Gaming.webp",
    title: "1x2 게이밍",
    logo: "/images/slot/logo/1x2_slot.webp",
    vendorId: "1x2Gaming",
  },
  {
    id: "slot-24",
    image: "/images/slot/slot_47.webp",
    title: "어거스트 게이밍",
    logo: "/images/slot/logo/office_slot.webp",
    vendorId: "august",
  },
  {
    id: "slot-25",
    image: "/images/slot/slot_48.webp",
    title: "게임피시 글로벌",
    logo: "/images/slot/logo/playngo_slot.webp",
    vendorId: "gamefish",
  },
  {
    id: "slot-26",
    image: "/images/slot/OneTouch.webp",
    title: "원터치 게이밍",
    logo: "/images/slot/logo/office_slot.webp",
    vendorId: "onetouch",
  },
  {
    id: "slot-27",
    image: "/images/slot/Thunderkick.webp",
    title: "썬더킥",
    logo: "/images/slot/logo/playngo_slot.webp",
    vendorId: "Thunderkick",
  },
  {
    id: "slot-28",
    image: "/images/slot/slot_52.webp",
    title: "스플릿락",
    logo: "/images/slot/logo/office_slot.webp",
    vendorId: "splitrock",
  },
  {
    id: "slot-29",
    image: "/images/slot/Mobilots.webp",
    title: "모빌럿",
    logo: "/images/slot/logo/playngo_slot.webp",
    vendorId: "Mobilots",
  },
  {
    id: "slot-30",
    image: "/images/slot/slot_54.webp",
    title: "아이언독",
    logo: "/images/slot/logo/office_slot.webp",
    vendorId: "irondog",
  },
  {
    id: "slot-31",
    image: "/images/slot/Kalamba.webp",
    title: "칼람바",
    logo: "/images/slot/logo/playngo_slot.webp",
    vendorId: "Kalamba",
  },
  {
    id: "slot-32",
    image: "/images/slot/Hacksaw.webp",
    title: "헥소게이밍",
    logo: "/images/slot/logo/playngo_slot.webp",
    vendorId: "Hacksaw",
  },
];
